Eks2/Eks2/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('forums/', include("forum.urls", namespace="forum")),
    path('posts/', include("posts.urls", namespace="posts")),
    path('people/', views.PeoplePage.as_view(), name='peeps'),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

Eks2/forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.ListForums.as_view(), name="all"),
    path("new/", views.CreateForum.as_view(), name="create"),
    path("posts/in/<slug>/",views.SingleForum.as_view(),name="single"),
    path("join/<slug>/",views.JoinForum.as_view(),name="join"),
    path("leave/<slug>/",views.LeaveForum.as_view(),name="leave"),
]

Eks2/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

Eks2/forum/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify

# pip install misaka
import misaka
from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

class Forum(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through='ForumMember')

    def __str__(self):
        return self.name

    def save(self, *arg, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('forum:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']
    pass

class ForumMember(models.Model):
    forum = models.ForeignKey(Forum,related_name='memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_forums',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('forum', 'user')

Eks2/forum/views.py
from django.contrib import messages
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)

from django.urls import reverse
from django.views.generic import (CreateView,DetailView,
                                ListView,RedirectView)
from forum.models import Forum,ForumMember
from . import models


class CreateForum(LoginRequiredMixin,CreateView):
    fields = ('name','description')
    model = Forum

class SingleForum(DetailView):
    model = Forum

class ListForums(ListView):
    model = Forum

class JoinForum(LoginRequiredMixin,RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('forum:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        forum = get_object_or_404(Forum,slug=self.kwargs.get("slug"))

        try:
            ForumMember.objects.create(user=self.request.user,forum=forum)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(forum.name)))

        else:
            messages.success(self.request,"You are now a member of the {}".format(forum.name))

        return super().get(request, *args, **kwargs)

class LeaveForum(LoginRequiredMixin,RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("forum:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        try:
            membership = models.ForumMember.objects.filter(
                user=self.request.user,
                forum__slug=self.kwargs.get("slug")
            ).get()

        except models.ForumMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this forum because you aren't in it."
            )

        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this forum."
            )
        return super().get(request, *args, **kwargs)

Eks2/forum/templates/forum/forum_base.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="row">
    {% block preforum%}{% endblock %}
    {% block contentforum%}{% endblock %}
    {% block postforum%}{% endblock %}
  </div>
</div>
{% endblock %}

Eks2/forum/templates/forum/forum_detail.html
{% extends 'forum/forum_base.html' %}
{% block preforum%}
<h1>{{forum.name}}</h1>
<h2>Member Count: {{forum.members.count}}</h2>

<div class="content">
  {% if user in forum.members.all %}
    <a href="{% url 'forum:leave' slug=forum.slug %}"
      class='btn btn-warning'><span
      class="glyphicon glyphicon-remove-circle"></span>Leave</a>
  {% else %}
    <a href="{% url 'forum:join' slug=forum.slug %}"
      class='btn btn-warning'><span
      class="glyphicon glyphicon-ok-circle"></span>Join</a>
  {% endif %}
</div>
{% endblock %}

{% block contentforum %}
<div class="col-md-8">
  {% if forum.posts.count ==0 %}
    <h2>No posts yet</h2>
  {% else %}
    {% for post in forum.posts.all %}
      {% include '_post.html' %}
    {% endfor %}
  {% endif %}
</div>
{% endblock %}

Eks2/forum/templates/forum/forum_form.html
{% extends 'forum/forum_base.html' %}
{% load bootstrap4 %}

{% block contentforum %}
<div class="container">
  <h4>Create new forum</h4>

    <form action="{% url 'forum:create' %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
    		<button type="submit" class="btn btn-primary btn-large">Create</button>
    	{% endbuttons %}
    </form>
</div>
{% endblock %}

Eks2/forum/templates/forum/forum_list.html
{% extends 'forum/forum_base.html' %}

{% block preforum%}

<div class="col-md-4">
  <div class="content">
    {% if user.is_authenticated %}
    <h2>Welcome Back! <a href="{% url 'posts:for_user' username=user.username%}">
      @{{user.username}}</a></h2>
    {% endif %}
    <h2>Forums</h2>
    <p>Welcome to forum page</p>
  </div>
  {% if user.is_authenticated %}
  <a href="{% url 'forum:create' %}" class="btn btn-warning">
    <span class="glyphicon glyphicon-plus-sign">Create new forum</span>
  </a>
  {% endif %}
</div>

{% endblock %}

{% block contentforum%}
<div class="col-md-8">
  <div class="list-group">
    {% for forum in object_list %}
    <a class="list-group-item" href="{% url 'forum:single' slug=forum.slug %}">
      <h3 class="title list-group-item-heading">{{forum.name}}</h3>
      <div class="list-group-item-text container-fluid">
        {{forum.description_html|safe}}
        <div class="row">
          <div class="col-md-4">
            <span class="badge">{{forum.members.count}}</span>
            member{{forum.members.count|pluralize}}
          </div>
          <div class="col-md-4">
            <span class="badge">{{forum.posts.count}}</span>
            post{{forum.posts.count|pluralize}}
          </div>
        </div>
      </div>
    </a>
    {% endfor %}

  </div>
</div>
{% endblock %}